<?xml version="1.0" encoding="utf-8"?><Database Name="NopBaiTapVeNha" Class="MyContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;Initial Catalog=NopBaiTapVeNha;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NopBaiTapVeNhaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BaiNop" Member="BaiNops">
    <Type Name="BaiNop">
      <Column Name="Ma" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaBaiTap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioNop" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FileLuu" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="BaiTap_BaiNop" Member="BaiTap" ThisKey="MaBaiTap" OtherKey="Ma" Type="BaiTap" IsForeignKey="true" />
      <Association Name="NguoiDung_BaiNop" Member="NguoiDung" ThisKey="Username" OtherKey="Username" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Quyen_NguoiDung" Member="Quyen_NguoiDungs">
    <Type Name="Quyen_NguoiDung">
      <Column Name="MaQuyen" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="NguoiDung_Quyen_NguoiDung" Member="NguoiDung" ThisKey="Username" OtherKey="Username" Type="NguoiDung" IsForeignKey="true" />
      <Association Name="Quyen_Quyen_NguoiDung" Member="Quyen" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="Quyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BaiTap" Member="BaiTaps">
    <Type Name="BaiTap">
      <Column Name="Ma" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HanNop" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AttachFile" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="BaiTap_BaiNop" Member="BaiNops" ThisKey="Ma" OtherKey="MaBaiTap" Type="BaiNop" />
      <Association Name="LopHoc_BaiTap" Member="LopHoc" ThisKey="MaLop" OtherKey="MaLop" Type="LopHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LopHoc" Member="LopHocs">
    <Type Name="LopHoc">
      <Column Name="MaLop" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GiaoVien" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LopHoc_BaiTap" Member="BaiTaps" ThisKey="MaLop" OtherKey="MaLop" Type="BaiTap" />
      <Association Name="NguoiDung_LopHoc" Member="NguoiDung" ThisKey="GiaoVien" OtherKey="Username" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="HoLot" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsLocked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastLoginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NguoiDung_BaiNop" Member="BaiNops" ThisKey="Username" OtherKey="Username" Type="BaiNop" />
      <Association Name="NguoiDung_Quyen_NguoiDung" Member="Quyen_NguoiDungs" ThisKey="Username" OtherKey="Username" Type="Quyen_NguoiDung" />
      <Association Name="NguoiDung_LopHoc" Member="LopHocs" ThisKey="Username" OtherKey="GiaoVien" Type="LopHoc" />
    </Type>
  </Table>
  <Table Name="dbo.Quyen" Member="Quyens">
    <Type Name="Quyen">
      <Column Name="MaQuyen" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQuyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Quyen_Quyen_NguoiDung" Member="Quyen_NguoiDungs" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="Quyen_NguoiDung" />
    </Type>
  </Table>
</Database>